# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-30 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField(default=0)),
                ('lon', models.IntegerField(default=0)),
                ('timestamp', models.CharField(max_length=140)),
                ('precipIntensity', models.CharField(max_length=140)),
                ('precipProbability', models.CharField(max_length=140)),
                ('dewPoint', models.CharField(max_length=140)),
                ('humidity', models.CharField(max_length=140)),
                ('pressure', models.CharField(max_length=140)),
                ('windSpeed', models.CharField(max_length=140)),
                ('cloudCover', models.CharField(max_length=140)),
                ('uvIndex', models.CharField(max_length=140)),
                ('ozone', models.CharField(max_length=140)),
            ],
        ),
    ]
