# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-30 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='lat',
            field=models.CharField(default=0, max_length=140),
        ),
        migrations.AlterField(
            model_name='weather',
            name='lon',
            field=models.CharField(default=0, max_length=140),
        ),
    ]
