# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-31 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180330_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('user_name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=500)),
                ('address', models.CharField(default=True, max_length=1000)),
                ('aadhar', models.CharField(default=True, max_length=16)),
                ('mobile', models.CharField(default=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='post_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ask', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LAT', models.CharField(default=True, max_length=100)),
                ('LON', models.CharField(default=True, max_length=100)),
                ('ALUM3S', models.CharField(default='45', max_length=100)),
                ('SNDPPT', models.CharField(default=True, max_length=100)),
                ('SLTPPT', models.CharField(default=True, max_length=100)),
                ('CLYPPT', models.CharField(default=True, max_length=100)),
                ('PHIHOX', models.CharField(default=True, max_length=100)),
                ('AWCH1', models.CharField(default=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='ques',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.post_question'),
        ),
    ]
